export const GET_REGISTRO_ADOPCIONES = "GET_REGISTRO_ADOPCIONES";
export const GET_REGISTRO_ADOPCION = "GET_REGISTRO_ADOPCION";
export const POST_REGISTRO_ADOPCION = "POST_REGISTRO_ADOPCION";
export const REGISTRO_ADOPCION_ERROR = "REGISTRO_ADOPCION_ERROR";
export const DELETE_REGISTRO_ADOPCION = "DELETE_REGISTRO_ADOPCION";
export const GET_REGISTRO_ADOPCIONES_ADMIN = "GET_REGISTRO_ADOPCIONES_ADMIN";
export const UPDATE_REGISTRO_ADOPCION_ADMIN = "UPDATE_REGISTRO_ADOPCION_ADMIN";

export const GET_REGISTRO_PERDIDOS = "GET_REGISTRO_PERDIDOS";
export const GET_REGISTRO_PERDIDO = "GET_REGISTRO_PERDIDO";
export const POST_REGISTRO_PERDIDO = "POST_REGISTRO_PERDIDO";
export const REGISTRO_PERDIDO_ERROR = "REGISTRO_PERDIDO_ERROR";
export const DELETE_REGISTRO_PERDIDO = "DELETE_REGISTRO_PERDIDO";
export const GET_REGISTRO_PERDIDOS_ADMIN = "GET_REGISTRO_PERDIDOS_ADMIN";
export const UPDATE_REGISTRO_PERDIDO_ADMIN = "UPDATE_REGISTRO_PERDIDO_ADMIN";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCCESS = "LOGIN_SUCCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";
